### ISSUE TITLE
Cannot run cargo when cross-compiling for Windows from Linux

### ISSUE THREAD

**Issue by jeysal** [rust-embedded/cross#550]
## Repro

In [a binary crate](https://github.com/jeysal/cross-run-cargo-repro) with the following code:

```rust
use std::process::Command;

fn main() {
    print!(
        "{}",
        String::from_utf8_lossy(
            &Command::new(env!("CARGO"))
                .arg("version")
                .output()
                .unwrap()
                .stdout
        )
    )
}
```

run `cross run --target "x86_64-pc-windows-gnu"` on x86_64 Linux.

## Expected

Like `cargo run`, prints
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/cross-run-cargo`
cargo 1.51.0 (43b129a20 2021-03-16)
```

## Actual

Errors trying to spawn the cargo process
```
   Compiling cross-run-cargo v0.1.0 (/project)
    Finished dev [unoptimized + debuginfo] target(s) in 0.38s
     Running `wine /target/x86_64-pc-windows-gnu/debug/cross-run-cargo.exe`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 6, kind: Other, message: "Invalid handle." }', src/main.rs:10:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I didn't find much regarding this error and unfortunately don't know much about `cross` internal workings. At first I thought it might just be a general "you're running a Linux binary on Windows/Wine", but a lot of people report Windows error 6 invalid handle in connection with terminal handles/std streams. Using piped streams doesn't seem to help, however.

**Comment by Alexhuszagh** [comment]
This still reproduces and doesn't occur with other targets, such as `aarch64-unknown-linux-gnu`. This is odd, since the hosted `CARGO` is native for `x86_64-unknown-linux-gnu`. Even more odd is if we change it from `env!("CARGO")` to `"cargo"`, the command doesn't find the executable, when it's on the path.

**Comment by Emilgardis** [comment]
it may be a wine issue

**Comment by Alexhuszagh** [comment]
Yep, it is: running on the host produces the following output:

```bash
$ wine target/x86_64-pc-windows-gnu/debug/cross-run-cargo.exe 
002c:fixme:winediag:LdrInitializeThunk wine-staging 7.10 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
00d8:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\vstor2-mntapi20-shared": c0000142
003c:fixme:service:scmdatabase_autostart_services Auto-start service L"vstor2-mntapi20-shared" failed to start: 1114
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/rust/bin"
CARGO="/rust/bin/cargo"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: NotFound, message: "program not found" }', src/main.rs:12:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

We might be able to see if the path can be added to the WINEPATH? Is that a terrible idea?

**Comment by Alexhuszagh** [comment]
I can get it to run using:

```bash
>start /unix /rust/bin/cargo --version
```

However, this doesn't give any output.
